import uuid

import pytest
from playwright.sync_api import APIRequestContext, Playwright

from clients.courses_client import CoursesApiClient
from config import settings


# --------------------------------------------------------------------------- #
# Users / auth                                                                #
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="session")
def test_user() -> dict[str, str]:
    """Primary seeded test user (env-overridable via config)."""
    return {"email": settings.test_user_email, "password": settings.test_user_password}


@pytest.fixture(scope="session")
def auth_headers() -> dict[str, str]:
    """HTTP Basic Authorization header for the primary test user."""
    return {"Authorization": settings.basic_auth_header, "Content-Type": "application/json"}


# --------------------------------------------------------------------------- #
# API layer                                                                   #
# --------------------------------------------------------------------------- #
@pytest.fixture(scope="session")
def api_client(playwright: Playwright) -> APIRequestContext:
    """Low-level Playwright API request context pointing at the backend."""
    request_context = playwright.request.new_context(base_url=settings.api_base_url)
    yield request_context
    request_context.dispose()


@pytest.fixture()
def courses_api(api_client: APIRequestContext) -> CoursesApiClient:
    """Typed Courses API client authenticated as the primary user."""
    return CoursesApiClient(api_client, auth_header=settings.basic_auth_header)


@pytest.fixture()
def other_courses_api(api_client: APIRequestContext) -> CoursesApiClient:
    """Typed Courses API client authenticated as a *different* user.

    Used for cross-user authorization tests (e.g. expecting 403 when acting on
    a course owned by someone else).
    """
    return CoursesApiClient(api_client, auth_header=settings.other_basic_auth_header)


# --------------------------------------------------------------------------- #
# Data lifecycle                                                              #
# --------------------------------------------------------------------------- #
@pytest.fixture()
def created_courses(courses_api: CoursesApiClient):
    """Track course IDs created during a test and delete them on teardown.

    Keeps the database clean between runs and makes parallel execution
    (`pytest -n auto`) safe by ensuring no test leaves shared state behind.
    Deletion is best-effort (already-gone courses are ignored).
    """
    course_ids: list[int] = []
    yield course_ids
    for course_id in course_ids:
        courses_api.delete_course(course_id)


@pytest.fixture()
def course_factory(courses_api: CoursesApiClient, created_courses: list[int]):
    """Return a callable that creates a valid course and auto-registers cleanup.

    Usage:
        course = course_factory()                     # sensible unique defaults
        course = course_factory(title="Custom Title") # override any field

    Returns a dict with the created ``id`` plus the payload that was sent, so
    setup for update/delete/get-by-id tests is one line and never repeats
    payload boilerplate.
    """
    def _make(**overrides) -> dict:
        payload = {
            "title": f"Factory Course - {uuid.uuid4().hex[:8]}",
            "description": "Auto-generated by the course factory.",
            "estimatedTime": "1 hour",
            "materialsNeeded": "None",
        }
        payload.update(overrides)
        response = courses_api.create_course(payload)
        assert response.status == 201, (
            f"course_factory failed to create a course: {response.status} {response.text()}"
        )
        course_id = response.json()["courseId"]
        created_courses.append(course_id)
        return {"id": course_id, **payload}

    return _make
